# nixpacks.toml

[phases.setup]
nixPkgs = ["libasound2-dev", "libgl1", "libglib2.0-0"]
python_version = "3.11"

[phases.build]
cmds = ['yarn run server:build']

[phases.start]
cmd = "gunicorn -w 4 -b :$PORT 'app:create_app()'"
