[build]
    builder = "Nixpacks"

[nixpacks]
    phases = {
        setup = "apt-get update && apt-get install -y portaudio19-dev", 
        install = "pip install -r requirements.txt", 
        start = "gunicorn app:app --bind 0.0.0.0:${PORT}" 
    }
