name: Build & Deploy Staging → EC2

on:
  push:
    branches:
      - staging

env:
  SSH_HOST: ${{ secrets.EC2_HOST }}
  SSH_USER: ${{ secrets.EC2_USER }}
  APP_DIR:  ${{ secrets.EC2_APP_DIR }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/talentora-analysis

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ env.APP_DIR }}
            # pull the newly-built image
            docker pull $IMAGE_NAME:${{ github.sha }}

            # stop & remove old container
            docker stop talentora-analysis    || true
            docker rm   talentora-analysis    || true

            # start fresh
            docker run -d \
              --name talentora-analysis \
              --restart unless-stopped \
              -p 8000:8000 \
              $IMAGE_NAME:${{ github.sha }}
