name: Build & Deploy Staging → EC2

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/talentora-analysis:$IMAGE_TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/talentora-analysis:$IMAGE_TAG

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker container prune --force
            docker image prune --all --force
            docker system prune --volumes --force
            
            cd ${{ secrets.EC2_APP_DIR }}

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/talentora-analysis:${{ github.sha }}

            docker stop talentora-analysis || true
            docker rm   talentora-analysis || true

            docker run -d \
              --name talentora-analysis \
              --restart unless-stopped \
              -p 8000:8000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/talentora-analysis:${{ github.sha }}
